/* eslint-disable no-console */
import { createWriteStream } from "node:fs";
import { mkdir, readdir, rm, stat, writeFile } from "node:fs/promises";
import { randomFillSync } from "node:crypto";
import { join, relative, resolve, sep } from "node:path";
import { computeFileFingerprintFromPath } from "../src/files.js";

type Entry = Readonly<{
  path: string;
  fileName: string;
  sizeBytes: number;
  fingerprint: `0x${string}`;
}>;

type GenerateConfig = Readonly<{
  enabled: boolean;
  count: number;
  minBytes: number;
  maxBytes: number;
  outDirRel: string; // repo-root relative, e.g. "resources/generated"
  clean: boolean;
}>;

const CONCURRENCY = 4;

function toPosixPath(p: string): string {
  return p.split(sep).join("/");
}

async function runWithConcurrency<T, R>(
  items: readonly T[],
  limit: number,
  worker: (item: T, idx: number) => Promise<R>
): Promise<R[]> {
  if (limit <= 0) throw new Error("runWithConcurrency: limit must be > 0");
  const out: R[] = new Array(items.length);
  let next = 0;

  const runWorker = async (): Promise<void> => {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      out[i] = await worker(items[i] as T, i);
    }
  };

  const workers = Array.from(
    { length: Math.min(limit, items.length) },
    () => runWorker()
  );
  await Promise.all(workers);
  return out;
}

async function walkFiles(dirAbs: string): Promise<string[]> {
  const out: string[] = [];
  const items = await readdir(dirAbs, { withFileTypes: true });
  for (const it of items) {
    // ignore dotfiles
    if (it.name.startsWith(".")) continue;
    const abs = join(dirAbs, it.name);
    if (it.isDirectory()) {
      const child = await walkFiles(abs);
      for (const p of child) out.push(p);
      continue;
    }
    if (!it.isFile()) continue;
    // ignore README and any manifest-like files
    if (it.name.toLowerCase() === "readme.md") continue;
    out.push(abs);
  }
  return out;
}

function renderTs(entries: readonly Entry[]): string {
  const header = `/**
 * GENERATED FILE — DO NOT EDIT BY HAND
 *
 * Generated by: \`pnpm util:resources:manifest\`
 */

import type { ResourceEntry } from "../types.js";

export const RESOURCES: readonly ResourceEntry[] = [
`;

  const body = entries
    .map((e) =>
      [
        "  {",
        `    path: ${JSON.stringify(e.path)},`,
        `    fileName: ${JSON.stringify(e.fileName)},`,
        `    sizeBytes: ${e.sizeBytes},`,
        `    fingerprint: ${JSON.stringify(e.fingerprint)} as \`0x\${string}\`,`,
        "  },",
      ].join("\n")
    )
    .join("\n");

  const footer = `
];
`;
  return `${header}${body}${footer}`;
}

function usageAndExit(): never {
  console.error(
    [
      "Usage:",
      "  pnpm exec tsx scripts/resources.ts",
      "",
      "Optional: generate random files before creating the manifest:",
      "  pnpm exec tsx scripts/resources.ts --generate --count <N> --min-bytes <n> --max-bytes <n> [--out-dir <repoRelDir>] [--clean]",
      "",
      "Notes:",
      "  - Sizes are BYTES (no units).",
      "  - If min-bytes == max-bytes, files are generated at that exact size.",
      "  - Safety cap: generation is limited to <= 15 GiB total (count * max-bytes).",
      `  - Concurrency: ${CONCURRENCY}`,
    ].join("\n")
  );
  process.exit(2);
}

function readArgValue(args: string[], key: string): string | undefined {
  const idx = args.indexOf(key);
  if (idx === -1) return undefined;
  return args[idx + 1];
}

function hasFlag(args: string[], key: string): boolean {
  return args.includes(key);
}

function parseIntStrict(raw: string | undefined, key: string): number | undefined {
  if (raw === undefined) return undefined;
  if (raw.trim().length === 0) return undefined;
  const n = Number(raw);
  if (!Number.isFinite(n) || !Number.isInteger(n)) {
    throw new Error(`Invalid ${key}: ${raw} (expected integer)`);
  }
  return n;
}

function parseGenerateConfig(argv: string[]): GenerateConfig {
  const enabled = hasFlag(argv, "--generate");
  if (!enabled) {
    return {
      enabled: false,
      count: 0,
      minBytes: 0,
      maxBytes: 0,
      outDirRel: "resources/generated",
      clean: false,
    };
  }

  const count = parseIntStrict(readArgValue(argv, "--count"), "--count");
  const minBytes = parseIntStrict(
    readArgValue(argv, "--min-bytes"),
    "--min-bytes"
  );
  const maxBytes = parseIntStrict(
    readArgValue(argv, "--max-bytes"),
    "--max-bytes"
  );
  const outDirRel = readArgValue(argv, "--out-dir") ?? "resources/generated";
  const clean = hasFlag(argv, "--clean");

  if (count === undefined || minBytes === undefined || maxBytes === undefined) {
    usageAndExit();
  }
  if (count <= 0) throw new Error("--count must be > 0");
  if (minBytes < 0) throw new Error("--min-bytes must be >= 0");
  if (maxBytes < 0) throw new Error("--max-bytes must be >= 0");
  if (maxBytes < minBytes) {
    throw new Error("--max-bytes must be >= --min-bytes");
  }

  return { enabled: true, count, minBytes, maxBytes, outDirRel, clean };
}

function pickSizeBytes(minBytes: number, maxBytes: number): number {
  if (minBytes === maxBytes) return minBytes;
  const span = maxBytes - minBytes + 1;
  return minBytes + Math.floor(Math.random() * span);
}

async function writeRandomFile(pathAbs: string, sizeBytes: number): Promise<void> {
  // Stream random bytes to disk to avoid large memory usage.
  const ws = createWriteStream(pathAbs, { flags: "w" });
  const CHUNK = 8 * 1024 * 1024; // 8 MiB
  let remaining = sizeBytes;

  await new Promise<void>((resolve, reject) => {
    ws.once("error", reject);
    ws.once("open", () => resolve());
  });

  try {
    while (remaining > 0) {
      const n = Math.min(CHUNK, remaining);
      const buf = Buffer.allocUnsafe(n);
      randomFillSync(buf);
      await new Promise<void>((resolve, reject) => {
        ws.write(buf, (err) => {
          if (err) reject(err);
          else resolve();
        });
      });
      remaining -= n;
    }
  } finally {
    await new Promise<void>((resolve) => ws.end(() => resolve()));
  }
}

async function generateRandomFiles(
  repoRoot: string,
  cfg: GenerateConfig
): Promise<void> {
  if (!cfg.enabled) return;

  const MAX_TOTAL_BYTES = 15n * 1024n * 1024n * 1024n; // 15 GiB safety cap per run
  const worstCase = BigInt(cfg.count) * BigInt(cfg.maxBytes);
  if (worstCase > MAX_TOTAL_BYTES) {
    throw new Error(
      `Refusing to generate: count*maxBytes=${worstCase.toString()} bytes exceeds 15GiB cap (${MAX_TOTAL_BYTES.toString()} bytes).`
    );
  }

  const outDirAbs = resolve(repoRoot, cfg.outDirRel);
  if (cfg.clean) {
    await rm(outDirAbs, { recursive: true, force: true });
  }
  await mkdir(outDirAbs, { recursive: true });

  console.log(
    `[manifest] generating ${cfg.count} random file(s) in ${cfg.outDirRel} (minBytes=${cfg.minBytes}, maxBytes=${cfg.maxBytes}, concurrency=${CONCURRENCY})`
  );

  const stamp = new Date()
    .toISOString()
    .replaceAll(":", "")
    .replaceAll(".", "")
    .replaceAll("-", "");

  const jobs: Array<Readonly<{ name: string; abs: string; size: number }>> = [];
  let plannedTotal = 0n;
  for (let i = 0; i < cfg.count; i++) {
    const size = pickSizeBytes(cfg.minBytes, cfg.maxBytes);
    plannedTotal += BigInt(size);
    const name = `rand-${stamp}-${String(i).padStart(5, "0")}.bin`;
    const abs = resolve(outDirAbs, name);
    jobs.push({ name, abs, size });
  }

  if (plannedTotal > MAX_TOTAL_BYTES) {
    throw new Error(
      `Refusing to generate: plannedTotal=${plannedTotal.toString()} bytes exceeds 15GiB cap (${MAX_TOTAL_BYTES.toString()} bytes).`
    );
  }

  await runWithConcurrency(jobs, CONCURRENCY, async (job) => {
    console.log(
      `[manifest] generating ${cfg.outDirRel}/${job.name} (${job.size} bytes)`
    );
    await writeRandomFile(job.abs, job.size);
    return null;
  });

  console.log(
    `[manifest] generated ${cfg.count} file(s), total=${plannedTotal.toString()} bytes`
  );
}

async function main(): Promise<void> {
  if (process.env.SKIP_RESOURCES_MANIFEST?.trim()) {
    console.log("[manifest] SKIP_RESOURCES_MANIFEST set; skipping generation");
    return;
  }

  const argv = process.argv.slice(2);
  if (hasFlag(argv, "--help") || hasFlag(argv, "-h")) usageAndExit();

  const repoRoot = resolve(process.cwd());
  const resourcesDir = resolve(repoRoot, "resources");
  const outFile = resolve(repoRoot, "src", "resources", "manifest.ts");

  const genCfg = parseGenerateConfig(argv);
  await generateRandomFiles(repoRoot, genCfg);

  const files = (await walkFiles(resourcesDir)).sort();
  if (files.length === 0) {
    console.error("[manifest] No files found under resources/. Add files and retry.");
    process.exit(2);
  }

  console.log(`[manifest] Scanning ${files.length} file(s) under resources/`);

  const entries = await runWithConcurrency(files, CONCURRENCY, async (abs) => {
    const st = await stat(abs);
    const relUnderResources = toPosixPath(relative(resourcesDir, abs));
    const path = toPosixPath(relative(repoRoot, abs));
    const fileName = relUnderResources.split("/").pop() ?? relUnderResources;
    console.log(`[manifest] hashing ${relUnderResources} (${st.size} bytes)`);
    const fingerprint = await computeFileFingerprintFromPath(abs);
    return {
      path,
      fileName,
      sizeBytes: st.size,
      fingerprint,
    } satisfies Entry;
  });

  // Keep output stable across runs regardless of concurrency scheduling.
  entries.sort((a, b) => a.path.localeCompare(b.path));

  const ts = renderTs(entries);
  await writeFile(outFile, ts, "utf8");
  console.log(`[manifest] wrote ${outFile}`);
}

await main();

